name: Update Big Lotto Numbers

on:
  schedule:
    - cron: '0 16 * * 3,6'

  workflow_dispath:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Crawl Big Lotto
        run: python BigLotto.py 
